<h1>handler</h1>

<h2>Syntax</h2>

<p>A <em>exceptionHandler</em> is:</p>

<p><strong>handler</strong> ( <em>id</em> )
<em>statementsAndDeclarations</em>
<strong>end</strong> <strong>handler</strong></p>

<h2>Description</h2>

<p>An exception handler  is an optional block of statements and declarations in a subprogram (or process). It is activated when the program (or process) fails. This occurs, for example when dividing by zero.</p>

<h2>Example</h2>

<p>This program parses the input stream using a stack. If the stack overflows (its top exceeds its maximum), a <strong>quit</strong> statement in the <em>push</em> procedure aborts the parsing and gives control to the exception handler in the <em>parse</em> procedure. The <em>parse</em> procedure calls <em>parseExpn</em> which calls <em>push</em>. If <em>push</em> overflows the stack, it executes a <strong>quit</strong> and control is passed to the exception handler in the <em>parse</em> procedure. The interrupted procedures (<em>parseExpn</em> and <em>push</em>) are terminated and their local variables are deleted.</p>

<pre><code>    const stackOverflow := 500
    const maxTop := 100
    var top : 0 .. maxTop := 0
    var stack : array 1 .. maxTop of int

    procedure push ( i : int )
        if top = maxTop then
            quit : stackOverflow
        end if
        top := top + 1
        stack ( top ) := i
    end push
    &#133;
    procedure parse
        handler ( exceptionNumber )
            put "Failure number ", exceptionNumber
            case exceptionNumber of
            label stackOverflow :
                put "Stack has overflowed!!"
            &#133; other exceptions handled here &#133;
            label :         % Unexpected failures
                quit &gt;      % Pass exception further
            end case
        end handler
        parseExpn           % Eventually push is called
    end parse
</code></pre>

<h2>Details</h2>

<p>See the <strong>quit</strong> statement for an explanation of its <em>quitReason</em> (<em>stackOverflow</em> in the first <strong>quit</strong> statement above) and its <em>guiltyParty</em> (> in the second <strong>quit</strong> statement, meaning the exception is due to causes outside of this handler).</p>

<p>An exception handler can appear only in the body of a subprogram (or process), just preceding the declarations and statements. The form of a procedure is:</p>

<p>Exactly the same declarations and statements can appear in a handler as can appear in the subprogram body following the handler. In the absence of exceptions, handlers have no observable effect. A particular handler is activated (it becomes ready to handle an exception) when it is encountered during execution. It remains active until the subprogram (or process) containing it has completed, or the handler is given control. Activation of a handler when a previous handler is already active will cause exceptions to be passed to the newly-activated handler. In other words, handlers have a dynamic scope that begins when the exception handler is encountered and ends when the subprogram (or process) containing the handler has terminated or the handler is given control.</p>

<p>When a handler is given control, it becomes, in effect, a replacement for the declarations and statements following it. If the handler is in a function, it must terminate with a <strong>result</strong> statement or with a <strong>quit</strong>. If the handler is in a procedure (or process), the handler must terminate with a <strong>return</strong>, a <strong>quit</strong>, or by encountering the end of the handler (which is equivalent to a <strong>return</strong>).</p>

<p>When a handler terminates with a <strong>result</strong> or <strong>return</strong> statement (or by reaching the end of a procedure's handler), the subprogram's <strong>post</strong> condition (if any) must be true. A <strong>quit</strong> statement does not need to establish the <strong>post</strong> condition.</p>

<p>Programming with exception handlers easily leads to incomprehensible software, due to the difficulty of keeping track of the flow of control. One of the most insidious situations is when an exception occurs in a module, class or monitor and is propagated outside of the unit. This can leave the contained data in an inconsistent state; in the case of a monitor, it is left locked forever. To avoid this possibility, you can use a handler in each exported subprogram. If an exception in a process is not handled, the entire program is aborted. If an implementation allocates dynamic arrays on the heap, an exception may prevent the deallocation of such an array.</p>

<p>Without exception handling, a program executes according to the language definition or else is aborted. If an exception handler is active, instead of aborting, control is given to the handler. The <em>quitNumber</em> for a system-detected failure is implementation-dependent. There is a file "<em>%exceptions</em>" which lists these numbers. The user program can simulate a system exception by doing a <strong>quit</strong> with the corresponding number.</p>

<p>If the user turns off checking  explicitly, the system may not detect failures. In some cases the failure may yield incorrect data or arbitrary behavior.</p>

<p>Some exceptions are unpredictable or implementation-dependent. For example, in <em>x</em> := 24 div <em>i</em> + 24 / <em>i</em>, if <em>i</em> is zero, the exception could be either an integer or a real division by zero, because the order or evaluation is implementation-dependent.</p>

<pre><code>    procedure [ pervasive ] id
        [ ( [ paramDeclaration {,paramDeclaration } ] ) ]
        [ import [ [var] id {, [var] id } ] ]
        [ pre trueFalseExpn ]
        [ init id := expn {, id := expn } ]
        [ post trueFalseExpn ]
        [ exceptionHandler ]
        statementsAndDeclarations
    end id
</code></pre>
